# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Virtual Account",
    "version": "14.0.1.15.3",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "contributors": [
        "Andhitia Rama <andhitia.r@gmail.com>",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "category": "Accounting",
    "depends": [
        "ssi_master_data_mixin",
        "ssi_localdict_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_financial_accounting",
        "ssi_partner",
    ],
    "external_dependencies": {
        "python": ["xlsxwriter"],
    },
    "data": [
        "security/ir_module_category/va_generator.xml",
        "security/res_groups/va_biller.xml",
        "security/res_groups/va_biller_merchant.xml",
        "security/res_groups/va_generator_type.xml",
        "security/res_groups/va_generator.xml",
        "security/res_groups/va_generator_exporter.xml",
        "security/ir_model_access/va_biller.xml",
        "security/ir_model_access/va_biller_merchant.xml",
        "security/ir_model_access/va_generator_type.xml",
        "security/ir_model_access/va_generator.xml",
        "security/ir_model_access/va_generator_exporter.xml",
        "security/ir_model_access/generate_va.xml",
        "security/ir_rule/va_generator.xml",
        "ir_sequence/va_generator.xml",
        "sequence_template/va_generator.xml",
        "approval_template/va_generator.xml",
        "policy_template/va_generator.xml",
        "menu.xml",
        "views/va_biller.xml",
        "views/va_biller_merchant.xml",
        "views/va_generator_type.xml",
        "views/va_generator.xml",
        "views/va_generator_exporter.xml",
        "views/ir_model.xml",
        "wizards/generate_va.xml",
    ],
    "demo": [],
}
