# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
#
# Migration: 14.0.1.15.15 -> 14.0.1.16.0
#
# Changes: va_generator.source_data gained three new columns:
#          generation_state (required, default "pending", already
#          backfilled to "pending" on every existing row by Odoo's
#          own _init_column when the column was created), acc_number,
#          and existing_bank_account_ids (m2m).
#
#          This script backfills generation_state = "generated" on
#          every source data row that belongs to a va_generator
#          already in the "done" state, since those rows already
#          produced their Virtual Account bank account(s) before this
#          feature existed and must not be re-evaluated as "pending"
#          the next time their document is touched.
#
#          acc_number and existing_bank_account_ids are deliberately
#          NOT backfilled: the res.partner.bank records generated by
#          a "done" va_generator are only linked back to the document
#          itself (res.partner.bank.va_generator_id), not to the
#          individual va_generator.source_data row that produced
#          them, so there is no way to recover which VA number (or
#          numbers, when a biller/merchant has more than one bank
#          code) belongs to which source data line. Those two columns
#          are left at their column default (NULL / empty) for
#          pre-existing rows.

import logging

from openupgradelib import openupgrade

_logger = logging.getLogger(__name__)


@openupgrade.migrate()
def migrate(env, version):
    """Stamp ``generation_state='generated'`` on rows of done documents.

    Every ``va_generator.source_data`` row whose parent
    ``va_generator`` is already ``state='done'`` already produced its
    Virtual Account bank account(s) before this feature existed, so
    it is stamped as ``"generated"`` rather than left at the
    ``"pending"`` default ``_init_column`` already wrote for every
    row. Rows belonging to a document in any other state are left
    untouched at ``"pending"``, matching the fresh-document lifecycle
    this feature introduces (evaluated at confirm, finalized at
    done).

    :param env: the migration environment
    :param version: the version being migrated to (unused)
    :return: nothing; updates ``va_generator_source_data`` rows
    """
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE va_generator_source_data AS source_data
        SET generation_state = 'generated'
        FROM va_generator AS generator
        WHERE generator.id = source_data.va_generator_id
        AND generator.state = 'done'
        """,
    )
    _logger.info(
        "Stamped generation_state='generated' on %s "
        "va_generator_source_data row(s) belonging to a done "
        "va_generator.",
        env.cr.rowcount,
    )
