# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import base64

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from odoo.addons.ssi_decorator import ssi_decorator


class VAGenerator(models.Model):
    """
    Represents a Virtual Account (VA) generation batch. Combines a biller
    (and, optionally, a merchant registered under that biller) with a
    generator type to compute unique VA codes for a set of source data
    records. When the document is set to done, it creates one
    ``res.partner.bank`` record (the generated Virtual Account) for
    every combination of source data and biller/merchant bank code.
    """

    _name = "va_generator"
    _description = "Virtual Account Generator"
    _inherit = [
        "mixin.transaction_cancel",
        "mixin.transaction_done",
        "mixin.transaction_confirm",
    ]

    # Multiple Approval Attribute
    _approval_from_state = "draft"
    _approval_to_state = "done"
    _approval_state = "confirm"
    _after_approved_method = "action_done"

    # Attributes related to add element on view automatically.
    # Done is reached automatically once approval completes (see
    # _after_approved_method above), so no manual "Done" button/policy
    # field is inserted on the form.
    _automatically_insert_view_element = True
    _automatically_insert_done_policy_fields = False
    _automatically_insert_done_button = False

    _statusbar_visible_label = "draft,confirm,done"
    _policy_field_order = [
        "confirm_ok",
        "approve_ok",
        "reject_ok",
        "restart_approval_ok",
        "cancel_ok",
        "restart_ok",
        "manual_number_ok",
    ]
    _header_button_order = [
        "action_confirm",
        "action_approve_approval",
        "action_reject_approval",
        "%(ssi_transaction_cancel_mixin.base_select_cancel_reason_action)d",
        "action_restart",
    ]

    # Attributes related to add element on search view automatically
    _state_filter_order = [
        "dom_draft",
        "dom_confirm",
        "dom_reject",
        "dom_done",
        "dom_cancel",
    ]

    # Sequence attribute.
    # NOTE: intentionally "done" (not "confirm") — of the mixins inherited
    # here (transaction_cancel/transaction_done/transaction_confirm), only
    # mixin.transaction_done reads _create_sequence_state, and only for the
    # value "done" (see ssi_transaction_done_mixin/models/
    # mixin_transaction_done.py::_prepare_done_data). "name" therefore stays
    # "/" until the document reaches done, matching the sq_letter/
    # incoming_letter precedent (same mixin combination).
    _create_sequence_state = "done"

    type_id = fields.Many2one(
        string="Generator Type",
        comodel_name="va_generator_type",
        required=True,
        readonly=True,
        states={"draft": [("readonly", False)]},
        help="Generator type whose python_code computes the unique VA "
        "code appended to the biller/merchant code for every generated "
        "Virtual Account number.",
    )
    biller_id = fields.Many2one(
        string="Biller",
        comodel_name="va_biller",
        required=True,
        readonly=True,
        states={"draft": [("readonly", False)]},
        help="Biller this generation batch is for. Determines the "
        "biller code(s) used when composing generated Virtual Account "
        "numbers.",
    )
    merchant_id = fields.Many2one(
        string="Merchant",
        comodel_name="va_biller_merchant",
        required=False,
        readonly=True,
        states={"draft": [("readonly", False)]},
        help="Optional merchant under the selected biller. When set, "
        "Virtual Account numbers are generated at merchant level using "
        "the merchant code registered for the selected biller. Left "
        "empty, Virtual Account numbers are generated at biller level.",
    )
    source_data_ids = fields.One2many(
        string="Source Data",
        comodel_name="va_generator.source_data",
        inverse_name="va_generator_id",
        readonly=True,
        help="Source records (e.g. partners) that Virtual Account "
        "numbers are generated for. Populated through a dedicated "
        "wizard (implemented separately) or directly via ORM — not "
        "meant to be filled in manually by the user.",
    )
    bank_account_ids = fields.One2many(
        string="Generated Bank Accounts",
        comodel_name="res.partner.bank",
        inverse_name="va_generator_id",
        readonly=True,
        help="Virtual Account bank accounts generated by this document "
        "once it reaches the done state.",
    )
    exporter_id = fields.Many2one(
        string="Exporter",
        comodel_name="va_generator_exporter",
        required=False,
        readonly=True,
        states={
            "draft": [("readonly", False)],
            "done": [("readonly", False)],
        },
        help="Layout and file format used when generating the export "
        "file for this document. Left editable in the done state as "
        "well, so a document that already reached done without one "
        "set can still be fixed without cancelling it (cancelling "
        "would delete every generated Virtual Account).",
    )

    @api.model
    def _get_policy_field(self):
        res = super(VAGenerator, self)._get_policy_field()
        policy_field = [
            "confirm_ok",
            "approve_ok",
            "done_ok",
            "cancel_ok",
            "reject_ok",
            "restart_ok",
            "restart_approval_ok",
            "manual_number_ok",
        ]
        res += policy_field
        return res

    @ssi_decorator.insert_on_form_view()
    def _insert_form_element(self, view_arch):
        if self._automatically_insert_view_element:
            view_arch = self._reconfigure_statusbar_visible(view_arch)
        return view_arch

    @ssi_decorator.pre_confirm_check()
    def _10_check_source_data(self):
        self.ensure_one()
        if not self.source_data_ids:
            error_message = """
Document Type: %s
Context: Confirm document
Database ID: %s
Problem: No source data has been added
Solution: Add at least one source data line before confirming
""" % (
                self._description,
                self.id,
            )
            raise UserError(_(error_message))

    @ssi_decorator.pre_confirm_check()
    def _20_check_merchant_biller_code(self):
        self.ensure_one()
        if not self.merchant_id:
            return
        if not self._get_merchant_biller_code_lines():
            error_message = """
Document Type: %s
Context: Confirm document
Database ID: %s
Problem: Merchant %s has no biller code registered for biller %s
Solution: Register a biller code for the merchant under the selected \
biller, or remove the merchant to generate Virtual Account numbers at \
biller level only
""" % (
                self._description,
                self.id,
                self.merchant_id.name,
                self.biller_id.name,
            )
            raise UserError(_(error_message))

    @ssi_decorator.pre_confirm_check()
    def _30_check_partner(self):
        self.ensure_one()
        for source in self.source_data_ids:
            try:
                self.type_id.generate_partner(
                    extra_localdict=self._get_partner_localdict(source)
                )
            except Exception as error:
                error_message = """
Document Type: %s
Context: Confirm document
Database ID: %s
Problem: Source data %s could not be resolved into a res.partner record: %s
Solution: Fix the generator type's partner resolution Python code so it \
resolves this source data line into a single res.partner record
""" % (
                    self._description,
                    self.id,
                    source.display_name,
                    error,
                )
                raise UserError(_(error_message))

    def _get_merchant_biller_code_lines(self):
        self.ensure_one()
        return self.merchant_id.biller_code_ids.filtered(
            lambda line: line.biller_id.va_biller_id == self.biller_id
        )

    @ssi_decorator.post_done_action()
    def _10_generate_bank_account(self):
        self.ensure_one()
        self._done()

    @ssi_decorator.post_cancel_action()
    def _10_delete_bank_account(self):
        self.ensure_one()
        self.bank_account_ids.unlink()

    def _done(self):
        self.ensure_one()
        schema_lines = self._get_bank_schema_lines()
        for source in self.source_data_ids:
            partner = self.type_id.generate_partner(
                extra_localdict=self._get_partner_localdict(source)
            )
            for schema in schema_lines:
                self._create_bank_account(source, partner, schema)

    def _get_partner_localdict(self, source):
        self.ensure_one()
        return {
            "generator": self,
            "source_data": source,
            "source_record": source.source_data_id,
            "biller": self.biller_id,
            "merchant": self.merchant_id,
        }

    def _get_bank_schema_lines(self):
        self.ensure_one()
        result = []
        if self.merchant_id:
            for line in self._get_merchant_biller_code_lines():
                result.append(
                    {
                        "bank": line.bank_id,
                        "biller_code_str": line.biller_id.biller_code,
                        "merchant_code_str": line.merchant_code,
                    }
                )
        else:
            for line in self.biller_id.bank_code_ids:
                result.append(
                    {
                        "bank": line.bank_id,
                        "biller_code_str": line.biller_code,
                        "merchant_code_str": "",
                    }
                )
        return result

    def _create_bank_account(self, source_data, partner, schema):
        self.ensure_one()
        unique_code = self.type_id.generate_code(
            extra_localdict={
                "biller": self.biller_id,
                "merchant": self.merchant_id,
                "bank": schema["bank"],
                "partner": partner,
                "source_data": source_data,
                "source_record": source_data.source_data_id,
            }
        )
        acc_number = "%s%s%s" % (
            schema["biller_code_str"],
            schema["merchant_code_str"],
            unique_code,
        )
        self.env["res.partner.bank"].create(
            self._prepare_bank_account_data(partner, schema["bank"], acc_number)
        )

    def _prepare_bank_account_data(self, partner, bank, acc_number):
        self.ensure_one()
        return {
            "partner_id": partner.id,
            "bank_id": bank.id,
            "acc_number": acc_number,
            "va_generator_id": self.id,
            "usage_id": self.type_id.usage_id.id,
        }

    def action_generate_export_file(self):
        for record in self.sudo():
            record._generate_export_file()

    def _generate_export_file(self):
        self.ensure_one()
        if self.state != "done":
            error_message = """
Document Type: %s
Context: Generate export file
Database ID: %s
Problem: Document is not in the done state
Solution: Generate the export file only after the document reaches done
""" % (
                self._description,
                self.id,
            )
            raise UserError(_(error_message))
        if not self.exporter_id:
            error_message = """
Document Type: %s
Context: Generate export file
Database ID: %s
Problem: No exporter has been selected
Solution: Select an exporter before generating the export file
""" % (
                self._description,
                self.id,
            )
            raise UserError(_(error_message))
        content = self.exporter_id.generate_file(
            extra_localdict=self._get_export_file_localdict()
        )
        self.env["ir.attachment"].create(
            self._prepare_export_file_attachment_data(content)
        )

    def _get_export_file_localdict(self):
        self.ensure_one()
        return {
            "generator": self,
            "biller": self.biller_id,
            "merchant": self.merchant_id,
            "bank_account_ids": self.bank_account_ids,
        }

    def _prepare_export_file_attachment_data(self, content):
        self.ensure_one()
        return {
            "name": self._get_export_file_name(),
            "res_model": self._name,
            "res_id": self.id,
            "type": "binary",
            "datas": base64.b64encode(content),
        }

    def _get_export_file_name(self):
        self.ensure_one()
        timestamp = fields.Datetime.now().strftime("%Y%m%d_%H%M%S")
        extension = self.exporter_id.get_file_extension()
        safe_name = (self.name or "").replace("/", "-")
        return "%s-%s.%s" % (safe_name, timestamp, extension)
